### ISSUE TITLE
Very low framerate

### ISSUE THREAD

**Issue by Like4Schnitzel** [maltejur/discord-screenaudio#163]
Running the Flatpak version on KDE Plasma I get very low framerates when sharing windows, whereas in the regular app it's fine with the same quality settings. There, what significantly increased the quality, was turning off OpenH264 Video Codec in the video codec settings, but those appear to be missing here.

**Comment by Growebis** [comment]
This is also happening to me on the compiled version as my friend reports the screensharing to be a slideshow.

**Comment by Like4Schnitzel** [comment]
Interestingly this has fixed itself for me. The quality is now reportedly smooth. I am unsure what caused this, but my best guess is that it was me updating my OS, PikaOS, to 23.04. Here's the changelog, perhaps it's possible to narrow it down to the cause:

* Disabled automatic suspend on live kde ISOs to prevent corruption and the password issue.
* Fixed xwayland rendering on the CPU instead of GPU when on Nvidia.
* Migrated from mintdrivers to pika-drivers. (rust gtk4 Libadwaita driver manager)
* Refined and refactored the gamescope-session and fixed many of it's bugs.
* Added steam-deck support just like nobara.
* Updated mangohud and gamescope to latest upstream
* Enabled nvml support for mangohud. (proper Nvidia support)
* Migrated from apx v1 to apx v2.
* Made Nvidia specific ISOs with Nvidia 535 pre configured and installed.
* Removed a lot of Gnome junk in kde ISOs

I don't have an Nvidia card and didn't install the update through an ISO, so that should rule out some of these.

**Comment by Like4Schnitzel** [comment]
I didn't mean to close the issue. My bad.

**Comment by disobeyedtoast** [comment]
> > Fixed xwayland rendering on the CPU instead of GPU when on Nvidia.
> 
> Sounds the most relevant

Unfortunately I doubt this is the issue, as I am running on X11 and an AMD system and still encounter the same stuttering effect.

**Comment by Kyr4l** [comment]
same issue with AMD GPU on Wayland

**Comment by nmlynch94** [comment]
Nvidia GPU on x11 seeing this as well.

**Comment by Lolotronop** [comment]
Nvidia GPU on Gnome Wayland on up to date Arch. Tried streaming a web browser (gnome Web and Firefox in this case) from PC to a laptop. Frame rate drops dramatically in dynamic scenes, but is fine on slow movement. Streaming gnome Web from Firefox does not lag nearly as hard or as often as streaming it from discord-screenaudio, but still drops some frames on 180 turns and huge in-game effects (tested on some Risk of Rain 2 footage on youtube). If somebody uses chrome here would be great if you could test it as well, maybe I'll get around to it tomorrow, but the issue seems to be exclusive to discord-screenaudio atm

**Comment by Lolotronop** [comment]
Same setup, tested streaming from Brave, as bad or worse than discord-screenaudio

**Comment by lou-perret** [comment]
Hello ! Same issue here, 7900 XTX with Wayland. Very, very bad framerate

On the official Discord app, I get nice framerate if I disable OpenH264, but I can't do that here :(

**Comment by jaykstah** [comment]
Chromium/Electron on Linux cannot do hardware video encoding at the moment, screen sharing will use software encoding on alternative clients like this. That's why the framerate is choppy from discord-screenaudio or from web browsers. Nothing the developers of this client can really do about it until a new version of Electron with this capability is made available.

**Comment by Lolotronop** [comment]
> Chromium/Electron on Linux
While QTWebEngine might use Chromium (which I don't think it does), discord-screenaudio definitely does not use Electron
With this out of the way, software encoding does not necessarily mean choppy video. With a mid range cpu you can stream with software encoding from OBS for example with much higher bitrate than what Discord has and still have a perfectly smooth image, OR use the official client and have perfectly fine framerate with OpenH264 (which I assume is the hardware video encoder-decoder) disabled as noted above by lou-perret. This is clearly a bug, but not a bug discord-screenaudio can fix unfortunately, since even Brave has the same problem (at least it had a month ago)

**Comment by brndd** [comment]
I have an i9 12900k which should be more than capable of software encoding 720p 30fps video, so it's weird that my streams apparently still have bad framerate.

**Comment by Yoss101** [comment]
Same issue on Nvidia 3080 Mobile and 11800h

**Comment by CorneliusCornbread** [comment]
I'm getting this issue on Fedora KDE 39, running the app through the terminal I get a lot of 
```
[OpenH264] this = 0x0x7fb8100c4d90, Warning:[Rc] iDid = 0,iContinualSkipFrames(147) is large
```
